image: python:3.8-buster

pages:
  stage: deploy
  image: python:latest
  script:
    - pip install mkdocs-material mkdocs-autorefs mkdocs-exclude mkdocs-get-deps mkdocs-glightbox mkdocs-material-extensions mkdocs-simple-hooks mkdocs-snippets
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
