apiVersion: k8s.f5.com/v1
kind: CNEInstance
metadata:
  labels:
    app.kubernetes.io/name: f5-lifecycle-operator
    app.kubernetes.io/managed-by: kustomize
  name: bnkgatewayclass-dpu
spec:
  product:
    gatewayAPI: true
    type: BNK
  manifestVersion: "2.2.0-3.2226.0-0.0.385"
  wholeCluster: true
  storageClassName: nfs
  dpu:
    enabled: true
  telemetry:
    loggingSubsystem:
      enabled: false
    metricSubsystem:
      enabled: true
  certificate:
    clusterIssuer: bnk-ca-cluster-issuer
      # deploymentSize: "Max"
  deploymentSize: "Large"
  registry:
    uri: repo.f5.com
    imagePullSecrets:
    - name: far-secret
    imagePullPolicy: Always
  networkAttachments:
  - sf-external
  - sf-internal
     
  # Features
  # CSRC Egress
  pseudoCNI:
    enabled: true
  # BGP
  dynamicRouting:
    enabled: true
  # Core dump files
  coreCollection:
    enabled: true
  # AFM
  firewallACL:
    enabled: true
 
  advanced:
    demoMode:
      enabled: false
    maintenanceMode:
      enabled: false
    envDiscovery:
      enabled: false
      stopOnFail: true
      runAfterSuccess: true
    cneController:
      env:
      - name: "TMM_DEFAULT_MTU"
        value: "9000"
    tmm:
      env:
      - name: "TMM_CALICO_ROUTER"
        value: "default"
      - name: "TMM_DEFAULT_MTU"
        value: "9000"
      - name: "ZEBOS_STATE"
        value: legacy
      #      - name: "TMM_LOG_LEVEL"
      #        value: "Debug" 
    #firewallACL:
    #  env:
    #  -name: "LOG_LEVEL"
    #   value: "info"
 
    #cwc:
    #  env:
    pseudoCNI:
      env:
      - name: "EXCLUDE_CIDR"
        value: "198.18.100.0/24,192.0.2.0/24,192.168.68.0/22"
