---
apiVersion: "k8s.f5net.com/v1"
kind: F5SPKVlan
metadata:
  name: external
spec:
  name: external
  mtu: 9000
  tag: 0
  interfaces:
    - "1.1"
  selfip_v4s:
    - 10.10.40.201
    - 10.10.40.202
  prefixlen_v4: 24
  selfip_v6s:
    - 2001::10:10:40:201
    - 2001::10:10:40:202
  prefixlen_v6: 64
  auto_lasthop: "AUTO_LASTHOP_ENABLED"
---
apiVersion: "k8s.f5net.com/v1"
kind: F5SPKVlan
metadata:
  name: internal
spec:
  name: internal
  mtu: 9000
  tag: 41
  interfaces:
    - "1.2"
  selfip_v4s:
    - 10.10.41.201
    - 10.10.41.202
  prefixlen_v4: 24
  selfip_v6s:
    - 2001::10:10:41:201
    - 2001::10:10:41:202
  prefixlen_v6: 64
  auto_lasthop: "AUTO_LASTHOP_ENABLED"
