network:
  version: 2
  renderer: networkd
  ethernets:

    ens16f0np0: 
      dhcp4: no
      dhcp6: no
      mtu: 9000
      addresses:
      - 10.10.40.109/24

  vlans:
    vlan41:
      id: 41
      link: ens16f0np0
      mtu: 9000
      addresses:
        - 10.10.41.109/24
