---
apiVersion: "k8s.f5net.com/v1"
kind: F5SPKVxlan
metadata:
  name: "red"
spec:
  name: "red"
  port: 4789
  key: 100
  # Interface name on host nodes that is used for underlay.
  # This is the previously configured Virtual Functionon PF1.
  remote_interface_name: "enp83s0f1v0"
  # Host nodes
  remote_nodes:
     # host node name in Kubernetes cluster.
   - node_name: "host-1"
     # Underlay IP address as configured on virtual function.
     # Change if different in your infrastructure.
     node_ip: "192.168.20.41"
     # Mac address and IP addresses that will be assigned to the
     # Host side VXLAN overlay interface.
     peer_mac: "00:f5:00:00:00:02"
     peerip_v4: "198.18.100.1"
     peerip_v6: "fd50::192:18:100:1"
   - node_name: "host-2"
     node_ip: "192.168.20.42"
     peer_mac: "00:f5:00:00:00:03"
     peerip_v4: "198.18.100.2"
     peerip_v6: "fd50::192:18:100:2"
   - node_name: "host-3"
     node_ip: "192.168.20.43"
     peer_mac: "00:f5:00:00:00:04"
     peerip_v4: "198.18.100.3"
     peerip_v6: "fd50::192:18:100:3"
  local_ips:
   - "192.168.20.201"
   - "192.168.20.202"
   - "192.168.20.203"
  selfip_v4s:
   - "198.18.100.201"
   - "198.18.100.202"
   - "198.18.100.203"
  prefixlen_v4: 24
  selfip_v6s:
   - "fd50::192:18:100:201"
   - "fd50::192:18:100:202"
   - "fd50::192:18:100:203"
  prefixlen_v6: 112
---
apiVersion: "k8s.f5net.com/v1"
kind: F5SPKVxlan
metadata:
  name: "blue"
spec:
  name: "blue"
  port: 4789
  key: 200
  remote_interface_name: "enp83s0f1v0"
  remote_nodes:
   - node_name: "host-1"
     node_ip: "192.168.10.41"
     peer_mac: "00:f5:01:00:00:02"
     peerip_v4: "198.18.200.1"
     peerip_v6: "fd50::192:18:200:1"
   - node_name: "host-2"
     node_ip: "192.168.10.42"
     peer_mac: "00:f5:01:00:00:03"
     peerip_v4: "198.18.200.2"
     peerip_v6: "fd50::192:18:200:2"
   - node_name: "host-3"
     node_ip: "192.168.10.43"
     peer_mac: "00:f5:01:00:00:04"
     peerip_v4: "198.18.200.3"
     peerip_v6: "fd50::192:18:200:3"
  local_ips:
   - "192.168.20.201"
   - "192.168.20.202"
   - "192.168.20.203"
  selfip_v4s:
   - "198.18.200.201"
   - "198.18.200.202"
   - "198.18.200.203"
  prefixlen_v4: 24
  selfip_v6s:
   - "fd50::192:18:200:201"
   - "fd50::192:18:200:202"
   - "fd50::192:18:200:203"
  prefixlen_v6: 112
