apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
    - name: default-ipv4-ippool
      blockSize: 26
      cidr: 192.168.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    bgp: Disabled
    nodeAddressAutodetectionV4:
      cidrs:
      - 10.144.0.0/16
---
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}