apiVersion: charts.k8s.f5net.com/v1alpha1
kind: SPKInfrastructure
metadata:
  name: bnk-dpu-infra
spec:
  networkAttachment:
  - name: default/sf-external
  - name: default/sf-internal
  platformType: other
  hugepages: true
  sriovResources:
    nvidia.com/bf3_p0_sf: "1"
    nvidia.com/bf3_p1_sf: "1"
  wholeClusterMode: "enabled"
  calicoRouter: "default"
  egress:
    json:
      ipPoolCidrInfo:
        ipPoolList:
        - name: pod_cidr_ipv4
          value: "192.168.0.0/16"
